version: '2'
services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
      BLAZER_DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
    depends_on:
      - db

volumes:
  pgdata:
